#ifndef E_CONSOLE_COLOURS_H_INCLUDED
#define E_CONSOLE_COLOURS_H_INCLUDED

#include "windows_funcs.h"

namespace Console
{
    #ifdef __WIN32
    enum class Foreground_Colour
    {
        BLACK             = 0,
        DARKBLUE          = FOREGROUND_BLUE,
        DARKGREEN         = FOREGROUND_GREEN,
        DARKCYAN          = FOREGROUND_GREEN    | FOREGROUND_BLUE,
        DARKRED           = FOREGROUND_RED,
        DARKMAGENTA       = FOREGROUND_RED      | FOREGROUND_BLUE,
        DARKYELLOW        = FOREGROUND_RED      | FOREGROUND_GREEN,
        DARKGRAY          = FOREGROUND_RED      | FOREGROUND_GREEN | FOREGROUND_BLUE,
        GRAY              = FOREGROUND_INTENSITY,
        BLUE              = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
        GREEN             = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
        CYAN              = FOREGROUND_INTENSITY | FOREGROUND_GREEN     | FOREGROUND_BLUE,
        RED               = FOREGROUND_INTENSITY | FOREGROUND_RED,
        MAGENTA           = FOREGROUND_INTENSITY | FOREGROUND_RED       | FOREGROUND_BLUE,
        YELLOW            = FOREGROUND_INTENSITY | FOREGROUND_RED       | FOREGROUND_GREEN,
        WHITE             = FOREGROUND_INTENSITY | FOREGROUND_RED       | FOREGROUND_GREEN | FOREGROUND_BLUE,
    };

    enum class Background_Colour
    {
        BLACK             = 0,
        DARKBLUE          = BACKGROUND_BLUE,
        DARKGREEN         = BACKGROUND_GREEN,
        DARKCYAN          = BACKGROUND_GREEN  | BACKGROUND_BLUE,
        DARKRED           = BACKGROUND_RED,
        DARKMAGENTA       = BACKGROUND_RED    | BACKGROUND_BLUE,
        DARKYELLOW        = BACKGROUND_RED    | BACKGROUND_GREEN,
        DARKGRAY          = BACKGROUND_RED    | BACKGROUND_GREEN | BACKGROUND_BLUE,
        GRAY              = BACKGROUND_INTENSITY,
        BLUE              = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
        GREEN             = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
        CYAN              = BACKGROUND_INTENSITY | BACKGROUND_GREEN   | BACKGROUND_BLUE,
        RED               = BACKGROUND_INTENSITY | BACKGROUND_RED,
        MAGENTA           = BACKGROUND_INTENSITY | BACKGROUND_RED     | BACKGROUND_BLUE,
        YELLOW            = BACKGROUND_INTENSITY | BACKGROUND_RED     | BACKGROUND_GREEN,
        WHITE             = BACKGROUND_INTENSITY | BACKGROUND_RED     | BACKGROUND_GREEN | BACKGROUND_BLUE,
    };
    #endif // __WIN32
}


#endif // E_CONSOLE_COLOURS_H_INCLUDED
